// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRM.Server.Data;

#nullable disable

namespace PRM.Server.Migrations
{
    [DbContext(typeof(PrmDbContext))]
    [Migration("20260618172328_RemoveSmtpCredentialsFromSystemConfigurations")]
    partial class RemoveSmtpCredentialsFromSystemConfigurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRM.Server.Models.Entities.ActivityTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("TagCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tag_category");

                    b.Property<string>("TagCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tag_code");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tag_name");

                    b.HasKey("Id");

                    b.HasIndex("TagCode")
                        .IsUnique();

                    b.ToTable("ACTIVITY_TAGS", (string)null);
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.AiRequestLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prompt");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("request_type");

                    b.Property<long>("RequestedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("ResponseSummary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_summary");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByUserId")
                        .HasDatabaseName("IX_AiLogs_User");

                    b.ToTable("AI_REQUEST_LOGS", (string)null);
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action_type");

                    b.Property<long>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entity_name");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_values");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.ToTable("AUDIT_LOGS", (string)null);
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.NotificationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryChannel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("delivery_channel");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("notification_type");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("recipient_email");

                    b.Property<long>("RecipientUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("recipient_user_id");

                    b.Property<long?>("RelatedEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("related_entity_name");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("subject");

                    b.Property<DateOnly?>("WeekStartDate")
                        .HasColumnType("date")
                        .HasColumnName("week_start_date");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId");

                    b.ToTable("NOTIFICATION_LOGS", (string)null);
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("health_status");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("LastRiskSummary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_risk_summary");

                    b.Property<long>("ManagerUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("manager_user_id");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("project_code");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("project_name");

                    b.Property<string>("ProjectStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("project_status");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("TotalStoryPoints")
                        .HasColumnType("int")
                        .HasColumnName("total_story_points");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ManagerUserId")
                        .HasDatabaseName("IX_Projects_Manager");

                    b.HasIndex("ProjectCode")
                        .IsUnique();

                    b.ToTable("PROJECTS", (string)null);
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.ProjectAllocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AllocatedByManagerId")
                        .HasColumnType("bigint")
                        .HasColumnName("allocated_by_manager_id");

                    b.Property<DateOnly>("AllocationEndDate")
                        .HasColumnType("date")
                        .HasColumnName("allocation_end_date");

                    b.Property<decimal>("AllocationPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("allocation_percentage");

                    b.Property<DateOnly>("AllocationStartDate")
                        .HasColumnType("date")
                        .HasColumnName("allocation_start_date");

                    b.Property<string>("AllocationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("allocation_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<long>("ResourceProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_profile_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AllocatedByManagerId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_Allocations_Project");

                    b.HasIndex("ResourceProfileId", "AllocationStatus", "AllocationStartDate", "AllocationEndDate")
                        .HasDatabaseName("IX_Allocations_ResourceProfile");

                    b.ToTable("PROJECT_ALLOCATIONS", (string)null);
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.ProjectMilestone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("MilestoneStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("milestone_status");

                    b.Property<string>("MilestoneTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("milestone_title");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.Property<int>("StoryPoints")
                        .HasColumnType("int")
                        .HasColumnName("story_points");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "DueDate")
                        .HasDatabaseName("IX_Milestones_Project");

                    b.ToTable("PROJECT_MILESTONES", (string)null);
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.ResourceProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("department");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("designation");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("employment_status");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsTimesheetFrozen")
                        .HasColumnType("bit")
                        .HasColumnName("is_timesheet_frozen");

                    b.Property<DateOnly?>("JoinedAt")
                        .HasColumnType("date")
                        .HasColumnName("joined_at");

                    b.Property<long?>("ManagerId")
                        .HasColumnType("bigint")
                        .HasColumnName("manager_id");

                    b.Property<string>("ResourceProfileCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("resource_profile_code");

                    b.Property<DateTime?>("TimesheetFrozenAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("timesheet_frozen_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("IX_ResourceProfiles_Manager");

                    b.HasIndex("ResourceProfileCode")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RESOURCE_PROFILES", (string)null);
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.ResourceProfileSkill", b =>
                {
                    b.Property<long>("ResourceProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_profile_id");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("proficiency_level");

                    b.HasKey("ResourceProfileId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("RESOURCE_PROFILE_SKILLS", (string)null);
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.SchedulerJobLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("job_name");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("SCHEDULER_JOB_LOGS", (string)null);
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.Skill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("skill_name");

                    b.HasKey("Id");

                    b.HasIndex("SkillName")
                        .IsUnique();

                    b.ToTable("SKILLS", (string)null);
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.SystemConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("config_value");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("ConfigKey")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("SYSTEM_CONFIGURATIONS", (string)null);
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.Timesheet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks");

                    b.Property<long>("ResourceProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_profile_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.Property<decimal>("TotalHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("total_hours");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date")
                        .HasColumnName("week_start_date");

                    b.HasKey("Id");

                    b.HasIndex("ResourceProfileId")
                        .HasDatabaseName("IX_Timesheets_ResourceProfile_Week");

                    b.HasIndex("ResourceProfileId", "WeekStartDate")
                        .IsUnique();

                    b.ToTable("TIMESHEETS", (string)null);
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.TimesheetComplianceTracking", b =>
                {
                    b.Property<long>("ResourceProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_profile_id");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date")
                        .HasColumnName("week_start_date");

                    b.Property<bool>("IsFrozenForWeek")
                        .HasColumnType("bit")
                        .HasColumnName("is_frozen_for_week");

                    b.Property<DateTime?>("LastReminderAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_reminder_at");

                    b.Property<short>("ReminderCount")
                        .HasColumnType("smallint")
                        .HasColumnName("reminder_count");

                    b.HasKey("ResourceProfileId", "WeekStartDate");

                    b.ToTable("TIMESHEET_COMPLIANCE_TRACKING", (string)null);
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.TimesheetLineItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("HoursLogged")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("hours_logged");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<long>("TimesheetId")
                        .HasColumnType("bigint")
                        .HasColumnName("timesheet_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly?>("WorkDate")
                        .HasColumnType("date")
                        .HasColumnName("work_date");

                    b.Property<string>("WorkNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("work_notes");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TimesheetId")
                        .HasDatabaseName("IX_LineItems_Timesheet");

                    b.ToTable("TIMESHEET_LINE_ITEMS", (string)null);
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.TimesheetLineItemActivityTag", b =>
                {
                    b.Property<long>("TimesheetLineItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("timesheet_line_item_id");

                    b.Property<long>("ActivityTagId")
                        .HasColumnType("bigint")
                        .HasColumnName("activity_tag_id");

                    b.Property<string>("CustomTagText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("custom_tag_text");

                    b.HasKey("TimesheetLineItemId", "ActivityTagId");

                    b.HasIndex("ActivityTagId");

                    b.ToTable("TIMESHEET_LINE_ITEM_ACTIVITY_TAGS", (string)null);
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("ForcePasswordChange")
                        .HasColumnType("bit")
                        .HasColumnName("force_password_change");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.AiRequestLog", b =>
                {
                    b.HasOne("PRM.Server.Models.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("PRM.Server.Models.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.NotificationLog", b =>
                {
                    b.HasOne("PRM.Server.Models.Entities.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.Project", b =>
                {
                    b.HasOne("PRM.Server.Models.Entities.User", "ManagerUser")
                        .WithMany()
                        .HasForeignKey("ManagerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagerUser");
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.ProjectAllocation", b =>
                {
                    b.HasOne("PRM.Server.Models.Entities.User", "AllocatedByManager")
                        .WithMany()
                        .HasForeignKey("AllocatedByManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRM.Server.Models.Entities.Project", "Project")
                        .WithMany("ProjectAllocations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRM.Server.Models.Entities.ResourceProfile", "ResourceProfile")
                        .WithMany("ProjectAllocations")
                        .HasForeignKey("ResourceProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AllocatedByManager");

                    b.Navigation("Project");

                    b.Navigation("ResourceProfile");
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.ProjectMilestone", b =>
                {
                    b.HasOne("PRM.Server.Models.Entities.Project", "Project")
                        .WithMany("Milestones")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.ResourceProfile", b =>
                {
                    b.HasOne("PRM.Server.Models.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PRM.Server.Models.Entities.User", "User")
                        .WithOne("ResourceProfile")
                        .HasForeignKey("PRM.Server.Models.Entities.ResourceProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.ResourceProfileSkill", b =>
                {
                    b.HasOne("PRM.Server.Models.Entities.ResourceProfile", "ResourceProfile")
                        .WithMany("ResourceProfileSkills")
                        .HasForeignKey("ResourceProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRM.Server.Models.Entities.Skill", "Skill")
                        .WithMany("ResourceProfileSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceProfile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.SystemConfiguration", b =>
                {
                    b.HasOne("PRM.Server.Models.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.Timesheet", b =>
                {
                    b.HasOne("PRM.Server.Models.Entities.ResourceProfile", "ResourceProfile")
                        .WithMany("Timesheets")
                        .HasForeignKey("ResourceProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceProfile");
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.TimesheetComplianceTracking", b =>
                {
                    b.HasOne("PRM.Server.Models.Entities.ResourceProfile", "ResourceProfile")
                        .WithMany("ComplianceTracking")
                        .HasForeignKey("ResourceProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceProfile");
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.TimesheetLineItem", b =>
                {
                    b.HasOne("PRM.Server.Models.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRM.Server.Models.Entities.Timesheet", "Timesheet")
                        .WithMany("LineItems")
                        .HasForeignKey("TimesheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Timesheet");
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.TimesheetLineItemActivityTag", b =>
                {
                    b.HasOne("PRM.Server.Models.Entities.ActivityTag", "ActivityTag")
                        .WithMany("LineItemTags")
                        .HasForeignKey("ActivityTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRM.Server.Models.Entities.TimesheetLineItem", "TimesheetLineItem")
                        .WithMany("ActivityTags")
                        .HasForeignKey("TimesheetLineItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityTag");

                    b.Navigation("TimesheetLineItem");
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.ActivityTag", b =>
                {
                    b.Navigation("LineItemTags");
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.Project", b =>
                {
                    b.Navigation("Milestones");

                    b.Navigation("ProjectAllocations");
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.ResourceProfile", b =>
                {
                    b.Navigation("ComplianceTracking");

                    b.Navigation("ProjectAllocations");

                    b.Navigation("ResourceProfileSkills");

                    b.Navigation("Timesheets");
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.Skill", b =>
                {
                    b.Navigation("ResourceProfileSkills");
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.Timesheet", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.TimesheetLineItem", b =>
                {
                    b.Navigation("ActivityTags");
                });

            modelBuilder.Entity("PRM.Server.Models.Entities.User", b =>
                {
                    b.Navigation("ResourceProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
